/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideNavbar: typeof import('./src/components/AsideNavbar/index.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    BreadcrumbTopbar: typeof import('./src/components/BreadcrumbTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    ExpandIcon: typeof import('./src/components/AsideNavbar/ExpandIcon.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Image: typeof import('primevue/image')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MyConfirm: typeof import('./src/components/MyConfirm.vue')['default']
    MyConfirmDialog: typeof import('./src/components/MyConfirmDialog.vue')['default']
    MyConfirmPopup: typeof import('./src/components/MyConfirmPopup.vue')['default']
    MyDialog: typeof import('./src/components/MyDialog.vue')['default']
    MyFileUpload: typeof import('./src/components/MyFileUpload.vue')['default']
    MyFormValidate: typeof import('./src/components/MyFormValidate.vue')['default']
    MyImageUpload: typeof import('./src/components/MyImageUpload.vue')['default']
    MyLoading: typeof import('./src/components/MyLoading.vue')['default']
    MyProgress: typeof import('./src/components/MyProgress.vue')['default']
    NavIcon: typeof import('./src/components/AsideNavbar/NavIcon.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryNav: typeof import('./src/components/AsideNavbar/SecondaryNav.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tag: typeof import('primevue/tag')['default']
    Tertiary: typeof import('./src/components/AsideNavbar/Tertiary.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
