/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/layouts': RouteRecordInfo<'/layouts', '/layouts', Record<never, never>, Record<never, never>>,
    '/layouts/home': RouteRecordInfo<'/layouts/home', '/layouts/home', Record<never, never>, Record<never, never>>,
    '/layouts/product/detail': RouteRecordInfo<'/layouts/product/detail', '/layouts/product/detail', Record<never, never>, Record<never, never>>,
    '/layouts/product/list': RouteRecordInfo<'/layouts/product/list', '/layouts/product/list', Record<never, never>, Record<never, never>>,
    '/layouts/product/otherproduct/detail': RouteRecordInfo<'/layouts/product/otherproduct/detail', '/layouts/product/otherproduct/detail', Record<never, never>, Record<never, never>>,
    '/layouts/product/otherproduct/list': RouteRecordInfo<'/layouts/product/otherproduct/list', '/layouts/product/otherproduct/list', Record<never, never>, Record<never, never>>,
    '/layouts/product/otherproduct/production': RouteRecordInfo<'/layouts/product/otherproduct/production', '/layouts/product/otherproduct/production', Record<never, never>, Record<never, never>>,
    '/layouts/todo/development': RouteRecordInfo<'/layouts/todo/development', '/layouts/todo/development', Record<never, never>, Record<never, never>>,
    '/layouts/todo/list': RouteRecordInfo<'/layouts/todo/list', '/layouts/todo/list', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
  }
}
